//
//  CalendarManager.swift
//  ScheduleSage
//
//  Created by CursorAI on 2024-03-20.
//

import EventKit
import Foundation
import AppKit
import SwiftDate

/// 日历管理器
public final class CalendarManager {
  // MARK: - Properties
  
  private let eventStore = EKEventStore()
  
  public init() {}
  
  // MARK: - Public Methods
  
  /// 请求日历访问权限
  public func requestAccess() async throws -> Bool {
    let status = EKEventStore.authorizationStatus(for: .event)
    
    switch status {
    case .authorized:
      return true
      
    case .notDetermined:
      return try await requestCalendarAccess()
      
    case .denied, .restricted:
      throw CalendarError.accessDenied
      
    case .writeOnly:
      throw CalendarError.writeOnlyAccess
      
    @unknown default:
      throw CalendarError.unknownStatus
    }
  }
  
  /// 创建日历事件
  /// - Parameter model: 日历事件模型
  /// - Returns: 创建的事件标识符
  @discardableResult
  public func createEvent(from model: CalendarEvent) async throws -> String {
    guard try await requestAccess() else {
      throw CalendarError.accessDenied
    }
    
    return try await createEventInternal(from: model)
  }
  
  /// 为所有日历设置自动生成的颜色
  public func setAutoGeneratedColorsForAllCalendars() async throws {
    guard try await requestAccess() else {
      throw CalendarError.accessDenied
    }
    
    try await setColorsInternal()
  }
  
  /// 获取所有日历
  public func getAllCalendars() -> [EKCalendar] {
    eventStore.calendars(for: .event)
  }
  
  /// 获取所有日历名称列表
  public func getAllCalendarNames() -> [String] {
    getAllCalendars().map(\.title)
  }
}

// MARK: - Private Methods
private extension CalendarManager {
  /// 请求日历访问权限
  func requestCalendarAccess() async throws -> Bool {
    try await withCheckedThrowingContinuation { continuation in
      if #available(macOS 14.0, *) {
        eventStore.requestFullAccessToEvents { granted, error in
          if let error = error {
            continuation.resume(throwing: error)
          } else {
            continuation.resume(returning: granted)
          }
        }
      } else {
        eventStore.requestAccess(to: .event) { granted, error in
          if let error = error {
            continuation.resume(throwing: error)
          } else {
            continuation.resume(returning: granted)
          }
        }
      }
    }
  }
  
  /// 创建事件的内部实现
  @discardableResult
  func createEventInternal(from model: CalendarEvent) async throws -> String {
    guard let calendar = try await getOrCreateCalendar(named: model.calendar) else {
      throw CalendarError.createFailed
    }
    
    // 验证日期转换
    guard let startDate = model.startDate.toDate()?.date,
          let endDate = model.endDate.toDate()?.date else {
      throw CalendarError.invalidDateFormat
    }
    
    let event = EKEvent(eventStore: eventStore)
    event.calendar = calendar
    event.title = model.title
    event.startDate = startDate
    event.endDate = endDate
    event.location = model.location
    event.url = URL(string: model.url)
    event.notes = model.notes
    
    try eventStore.save(event, span: .thisEvent)
    return event.eventIdentifier
  }
  
  /// 获取或创建日历
  func getOrCreateCalendar(named name: String) async throws -> EKCalendar? {
    // 检查是否存在同名日历
    if let existingCalendar = eventStore.calendars(for: .event).first(where: { $0.title == name }) {
      return existingCalendar
    }
    
    // 创建新日历
    let newCalendar = EKCalendar(for: .event, eventStore: eventStore)
    newCalendar.title = name
    
    // 设置日历源
    if let source = eventStore.sources.first(where: { $0.sourceType == .local }) 
      ?? eventStore.defaultCalendarForNewEvents?.source {
      newCalendar.source = source
    } else {
      return nil
    }
    
    try eventStore.saveCalendar(newCalendar, commit: true)
    return newCalendar
  }
  
  /// 设置日历颜色的内部实现
  func setColorsInternal() async throws {
    let calendars = getAllCalendars()
    
    for calendar in calendars {
      let hexColor = try await generateColorForCalendar(named: calendar.title)
      if let color = colorFromHex(hexColor) {
        calendar.cgColor = color.cgColor
        try eventStore.saveCalendar(calendar, commit: false)
      }
    }
    
    try eventStore.commit()
  }
  
  /// 根据日历名生成颜色
  func generateColorForCalendar(named name: String) async throws -> String {
    // TODO: 这里应该调用 LLM API 来生成颜色
    // 目前使用简单的哈希算法作为临时实现
    let hash = name.hash
    let hue = abs(Double(hash % 360)) / 360.0
    let saturation = 0.7 + Double(abs(hash % 30)) / 100.0
    let brightness = 0.8 + Double(abs(hash % 20)) / 100.0
    
    let color = NSColor(hue: hue, saturation: saturation, brightness: brightness, alpha: 1.0)
    return String(
      format: "#%02X%02X%02X",
      Int(color.redComponent * 255),
      Int(color.greenComponent * 255),
      Int(color.blueComponent * 255)
    )
  }
  
  /// 从十六进制字符串创建颜色
  func colorFromHex(_ hex: String) -> NSColor? {
    var hexSanitized = hex.trimmingCharacters(in: .whitespacesAndNewlines)
    hexSanitized = hexSanitized.replacingOccurrences(of: "#", with: "")
    
    var rgb: UInt64 = 0
    guard Scanner(string: hexSanitized).scanHexInt64(&rgb) else {
      return nil
    }
    
    return NSColor(
      red: CGFloat((rgb & 0xFF0000) >> 16) / 255.0,
      green: CGFloat((rgb & 0x00FF00) >> 8) / 255.0,
      blue: CGFloat(rgb & 0x0000FF) / 255.0,
      alpha: 1.0
    )
  }
}

// MARK: - Error Types
extension CalendarManager {
  enum CalendarError: LocalizedError {
    case accessDenied
    case writeOnlyAccess
    case unknownStatus
    case colorGenerationFailed
    case createFailed
    case invalidDateFormat
    
    var errorDescription: String? {
      switch self {
      case .accessDenied:
        return NSLocalizedString("calendar.error.access_denied",
                               comment: "Error message when calendar access is denied")
      case .writeOnlyAccess:
        return NSLocalizedString("calendar.error.write_only_access",
                               comment: "Error message when only write access is granted")
      case .unknownStatus:
        return NSLocalizedString("calendar.error.unknown_status",
                               comment: "Error message for unknown permission status")
      case .colorGenerationFailed:
        return NSLocalizedString("calendar.error.color_generation_failed",
                               comment: "Error message when color generation fails")
      case .createFailed:
        return NSLocalizedString("calendar.error.create_failed",
                               comment: "Error message when calendar creation fails")
      case .invalidDateFormat:
        return NSLocalizedString("calendar.error.invalid_date_format",
                               comment: "Error message when date format is invalid")
      }
    }
  }
}
